### ISSUE TITLE
Consider use of JSON0 text type?

### ISSUE THREAD

**Issue by curran** [ejones/sharedb-codemirror#1]
Greetings,

Thank you for your work on this library.

I'd like to use sharedb-codemirror to add code editing functionality to an existing ShareDB application. However, the existing application uses the [JSON0 text type](https://github.com/ottypes/json0#string-operations) (`text0`) for strings. Since sharedb-codemirror uses the [`text` OT type](https://github.com/ottypes/text), I am not able to use it in the existing application (without modifying the existing application to use the `text` type).

Would you be open to accepting a PR that adds an option to use the `text0` OT type? It seems like it would be pretty straightforward to do by modifying all the places where OPs are generated. Thank you.

**Comment by ejones** [comment]
Hey @curran - thanks for your interest!

For sure, we could add an option to generate `text0` ops instead of `text` ops.

**Comment by curran** [comment]
Hi @ejones - thanks for your reply!

It's good to know you'd be open to this. I was thinking the API could make use of the existing options structure, so starting it off might look something like this:

```js
ShareDBCodeMirror.attachDocToCodeMirror(doc, editor, {
  key: 'content',
  verbose: true,
  type: 'text0'
});
```

Does that look good to you? If so I can take some initiative to start an implementation. With respect to the tests, I think we'd want to invoke all the tests as they are now twice, once with the `text` type, and again with the `text0` type.

**Comment by ejones** [comment]
Yep - makes sense. The current tests could be made into shared test suites parameterized by the OT type. The tests use a class, `MockDoc`, that mocks out the OT operations and work normally done by ShareDB's `Doc`, so I guess that would need to be made to understand `text0` as well.

**Comment by curran** [comment]
I ended up solving this by rolling my own library, [codemirror-binding](https://github.com/curran/CodeMirrorBinding) by porting [sharedb-string-binding](https://github.com/share/sharedb-string-binding) and [https://github.com/share/text-diff-binding](https://github.com/share/text-diff-binding) to work with the CodeMirror API instead of the DOM text input API. This implementation has a few features that sharedb-codemirror does not, such as handling arbitrary document paths, and cursor/selection transforms, which are things I needed for my use case.
